enum Operator {

  IS_EQUALS,
  IS_EQUALS_IGNORE_CASE,

  NOT_EQUALS,
  NOT_EQUALS_IGNORE_CASE,

  IS_CONTAINS,
  IS_CONTAINS_IGNORE_CASE,

  NOT_CONTAINS,
  NOT_CONTAINS_IGNORE_CASE,

  IS_STARTS_WITH,
  IS_STARTS_WITH_IGNORE_CASE,

  NOT_STARTS_WITH,
  NOT_STARTS_WITH_IGNORE_CASE,

  IS_ENDS_WITH,
  IS_ENDS_WITH_IGNORE_CASE,

  NOT_ENDS_WITH,
  NOT_ENDS_WITH_IGNORE_CASE,

  IS_REGEX_MATCH,
  IS_REGEX_MATCH_IGNORE_CASE,

  NOT_REGEX_MATCH,
  NOT_REGEX_MATCH_IGNORE_CASE,

  LESS_THAN,
  LESS_THAN_OR_EQUALS,
  GREATER_THAN,
  GREATER_THAN_OR_EQUALS,
}

export default Operator;